demo/.vscode/ruby.rb

Referencing #19 
Added a ruby demo file, wasn't sure what all you wanted in there so I added some gibberish ruby that would display the incorrect colorization I noticed.

Added a ruby demo file

---

themes/Night Owl-color-theme.json

Addresses #20 
Sorry about the formatting changes. I'm on my other machine at the moment and it doesn't have all my usual setup.

fix input prompt highlight

---

themes/Night Owl-color-theme.json

Fix peek result color contrast

---

themes/Night Owl-color-theme.json

This PR fixes this issue https://github.com/sdras/night-owl-vscode-theme/issues/33

Coloring operators

---

themes/Night Owl-color-theme.json

Fix contrast of selection highlight in search input

---

themes/Night Owl-color-theme.json

This fixes https://github.com/sdras/night-owl-vscode-theme/issues/53.

Fixing PHP accessing property color

---

demo/powershell.ps1

Powershell file example for #63

add ps1 example

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This fixes https://github.com/sdras/night-owl-vscode-theme/issues/66

Support for 'Git Commit Message' language mode

---

README.md

Thanks so much for this theme and these great docs on it!
It’s my first time installing a visual studios theme, and the guide on how to do it saved me some headaches.
One headache I still found was that the preferences option was under `Code` not `File` (on a mac), so here's a quick PR to update that. Hope this is helpful.

Slightly clearer docs

---

demo/ruby.rb
themes/Night Owl-color-theme.json

Italicize the module/class keyword in ruby.

---

demo/tsx.tsx
themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This closes https://github.com/sdras/night-owl-vscode-theme/issues/78

Fixing import/from colors on .tsx files

---

demo/issue-91.jsx
demo/issue-91.tsx
themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This closes #91
I have only fixed the basic bugs based on the code provided. If there are any additional bugs then please update 
- demo/issue-91.jsx
- demo/issue-91.tsx
These test files inside **demo** folder and I will debug & try to fix those bugs asap.
Regards!

Added basic react in TS support

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This closes https://github.com/sdras/night-owl-vscode-theme/issues/95

Fixing ts and js differences

---

README.md

This PR Adds the link to the vim port of this amazing theme

Add vim theme link

---

README.md

Title says it all I guess, it has been added, and it is lit! It also is iTerm 2

Added my 🔥 iTerm 2 theme adaptation

---

README.md

Notably, it's only a little tested, but it compares well to C and Markdown right now (within the limitations of the lexers).

Add link to Pygments version of theme

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

Fixes this issue: https://github.com/sdras/night-owl-vscode-theme/issues/108

Go coloring

---

demo/js.js
demo/typescript.ts
themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This fixes https://github.com/sdras/night-owl-vscode-theme/issues/118

Improving colors on ts files

---

README.md

- screenshot
- ![screenshot](https://monosnap.com/image/K3aJzPi36YMphPcbjCvJ9HAubsgkkb.png)

add new vim port of the theme.

---

README.md

This PR updates README.md with a link to Night Owl Alfred theme 🎉

add Night Owl Alfred theme to README

---

README.md

Hi,
I have created a theme for Insomnia based on Night Owl. Here is the changes to update the README to link to the theme homepage.
Hope it will be useful 😃

add Insomnia theme to README

---

demo/cplusplus-header.h
demo/cplusplus-source.cc

I used large files directly from V8's source so that there's no scope of me missing out some crucial language features. I'm positive that the two files have almost everything C++ has to offer.
@sdras perhaps this would help you improve highlighting C++ source? Sorry it took me so long to make it.

Add C++ source file and header to demos

---

README.md

I've been working on a port for Sublime Text (just the color scheme). I believe is in a usable state now.
Feedback and contributions are welcome.

Added Sublime Text 3 color scheme link in the README.md

---

README.md

This is a initial proposal about color scheme for Slack
I hope you like it! 🦉

Included color scheme for Slack on README file

---

README.md

For issue https://github.com/sdras/night-owl-vscode-theme/issues/177#issue-429244499

Update code to Separate Editor & Sidebar only for this theme only

---

README.md
themes/Night Owl-Light-color-theme-noitalic.json
themes/Night Owl-Light-color-theme.json
themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

update theme name and add color to instanceOf operator

---

README.md

Added the link to the XCode Night Owl theme.

Added Link to Night Owl - Xcode

---

demo/csharp.cs
demo/flutter.dart

Added two more files in the `demo` folder for CSharp and Dart (in this case, with a file from a Flutter project) to request a better "colorizing" in VSCode.
The CSharp one is covered by the Visual Studio plugin, but I didn't find anyone that made it for Dart in any other editor.
I will follow your "How to" to understand the structure of the plugin and try to correct the colors.

Added demos for C# and Dart (Flutter)

---

themes/Night Owl-Light-color-theme-noitalic.json

Fixes #194 
Copied the color from italic to non-italic.

Issue 194 - Fix discrepancy between light themes

---

README.md

I created a port of the theme for Ulauncher. An application launcher for Linux.
I thought it would be nice to reference it here for other people to discover more easily.

Add reference to Ulauncher port

---

README.md

Hello,
I created an Alacritty setting of your wonderful theme. It can be found  in the wiki section of the git repo.

alacritty config

---

README.md

Hi!
I ported Light Owl to Tilix. Might need some tweaking, suggestions welcome :)

Add Light Owl theme for Tilix

---

README.md

Added support for Visual Studio 2022. 
Also fixes #314

Added VS 2022 support
