themes/Night Owl-color-theme.json

Thank you for working on this theme!
I noticed that the placeholders' foreground colors are the same as that of normal text colors. This creates a slight confusion while searching.
Before:
After:

Change foreground color for placeholders

---

themes/Night Owl-color-theme.json

Hello Sarah, great theme!
Just a tiny fix for those of us who use editor.rulers setting for keeping track of line lengths.
The ruler now uses the same blue as the indentation lines, instead of the standard grayish color.
Before:
After:
Thanks!

fix editor ruler color

---

themes/Night Owl-color-theme.json

This fixes https://github.com/sdras/night-owl-vscode-theme/issues/49.
Turns out that the issue was not only on `.ts` files.

Fixing inconsistent italics

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This fixes https://github.com/sdras/night-owl-vscode-theme/issues/60
Before:
After:

Increase contrast for line number foreground

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This closes https://github.com/sdras/night-owl-vscode-theme/issues/79
This is how it looks now after the changes we talked about on https://github.com/sdras/night-owl-vscode-theme/pull/81:

Making the cursor more visible with a bright blue color

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This closes https://github.com/sdras/night-owl-vscode-theme/issues/88
This is how it looks now:

Adding a lighter color for Active Indent Guide

---

themes/Night Owl-color-theme.json

How it looks now in JS/JSX/TS/TSX

Fix get/set, storage.type (was overridden)

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This closes https://github.com/sdras/night-owl-vscode-theme/issues/99
Here how it looks:

Fixing tab bar color when showTabs is false

---

themes/Night Owl-color-theme-noitalic.json

Same as https://github.com/sdras/night-owl-vscode-theme/pull/110, but for non-italic version. I just forgot to include it here :(

Fix get/set, storage.type (was overridden) - non italic

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This fixes https://github.com/sdras/night-owl-vscode-theme/issues/115
This is how it looks now:

Changing active panel title color

---

README.md

Thanks for the awesome theme Sarah. I've also authored a [purple VSCode theme](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple). The shields badge for downloads which was working alright is now buggy. It was reporting fewer downloads than actual so I removed it.
I first thought it was only for my theme but apparently, it's reporting 20k fewer downloads for Night Owl as well. So, I figured you'd want to remove it.
I replaced it with the reviews badge.

🐛 FIX: Replace the buggy shields bagde

---

README.md

* Closes #128 
* Adds TextMate, Ace Editor and RStudio theme ports to README (all three generated from the TextMate theme, but the Ace and RStudio themes have been modified to add features not supported in the original conversion).
🌌🦉💖

Add TextMate, Ace, and RStudio themes to README.

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

Added markdown coloring for an inline raw string inside backticks.
Closes #141

Added markdown coloring

---

themes/Night Owl-color-theme-noitalic.json

Italics were showing up in .diff files. This fixes that.
Addresses https://github.com/sdras/night-owl-vscode-theme/issues/153

No Italics Theme: Remove italics from git diff

---

demo/ruby.rb
themes/Night Owl-color-theme.json

Tiny fix, I noticed that symbol syntax wasn't getting picked up for Ruby:
I added to the demo example and now it's differentiating symbols like this:
I'm by no means design-inclined, so if a different color would be more appropriate I'm definitely open to other options. 
The theme is great, by the way! Hope this helps.

Add symbol highlighting and add to demo

---

.vscode/settings.json
demo/python.py
themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

fixes #143 
Fixed 
- bad coloring for `from`, `import`, `if`, `for`, `return` keywords
- different color for function names
- italic support for function names
before:
after:

fix python keywords color

---

README.md

Possible fix/workaround for https://github.com/Microsoft/vscode/issues/69810.
I noticed `night-owl-vscode-theme` isn't a thing that appears in the name, or keywords, only appearing as [part of the url](https://github.com/sdras/night-owl-vscode-theme/blob/f383bdbeabb54b04584d009af1e8acab2c868a95/package.json#L10).
We could try to search for something else, like `night-owl`, which is the name [specified for the package](https://github.com/sdras/night-owl-vscode-theme/blob/f383bdbeabb54b04584d009af1e8acab2c868a95/package.json#L2)?

Tweak `README` to suggest a better marketplace search term

---

CHANGELOG.md
package.json
themes/Night Owl-Light-color-theme-noitalic.json

I took a stab at creating the "no-italic" variation of the new light theme. I removed italic font styles from everything except `italics` and `markdown italics`, which seems to mirror the original.

Create non-italic light theme

---

README.md

Searching `night-owl` on VS code does not show this package. The right search term is `night owl`. So, Updating the README with proper package name.
**Before**
**After**

Updating right package name

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

Fixes #223 
Currently `constrastActiveBorder` causes distortion on some command pallets that have descriptions such as the python `configure tests` pallet.
This looks like it might be an issue w/ adding `contrastActiveBorder` styling to any vscode theme.

Issue 223 - Fix text distortion on certain command pallets

---

themes/Night Owl-Light-color-theme-noitalic.json
themes/Night Owl-Light-color-theme.json

@sdras made a similar change in #193, specifically commit https://github.com/sdras/night-owl-vscode-theme/commit/96279d23bfb3094ac1d6b16fc586c90fb678a515
This addresses #218 and updates the rest of the invalid token colors. (This is a refresh of #219)
In simple terms, many invalid tokens use a background color with white text — but since background colors aren't supported, the result is just white text:
So in this PR I swap the background color to the foreground, and remove the background declaration.
Thanks for the reminder @macguirerintoul

Fix invalid token colors

---

CHANGELOG.md
package.json
themes/Night Owl-Light-color-theme-noitalic.json
themes/Night Owl-Light-color-theme.json
themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

This is a patch that fixes the typescript variable class keyword highlighting issue referenced in #237. Open to feedback on the selector choice as this is my first time editing a VSCode theme!
If anyone is looking for a fix for this before this pull request is merged, you can find the VSIX extension file [here](https://github.com/sfred/night-owl-vscode-theme/releases/tag/1.1.4).

Fixed typescript highlighting issue #237

---

README.md

I've created a port of Night Owl to Xresources, which is a configuration file for some X client applications (e.g., urxvt and xterm).

Add Xresources port reference to README

---

themes/Night Owl-color-theme.json

I use a lot of JSDocs in my TypeScript code and sometimes include backticks to refer to code parts. The background color for this was very dark and not distinguishable. I made it into a lighter grey so it is much more readable.
Below is a screenshot of my update

Update code background color in hover contents

---

README.md

Add Night Owl and Light Owl themes for Alacritty terminal.

Add Night Owl and Light Owl themes for Alacritty

---

themes/Night Owl-Light-color-theme-noitalic.json
themes/Night Owl-Light-color-theme.json
themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

Added `punctuation.definition.comment` to the Comment scope to enable transforms (highlight, diff) in `shiki` code highlighter.

Fix: enable comment transforms in `shiki` code highlighter

---

README.md

This adds a preview badge for vscode.dev that goes to https://vscode.dev/theme/sdras.night-owl
And a preview of the theme in vscode.dev:
More info about vscode web + themes https://code.visualstudio.com/docs/editor/vscode-web#_themes

Add vscode.dev theme preview badge

---

themes/Night Owl-Light-color-theme-noitalic.json
themes/Night Owl-Light-color-theme.json

editor inlay hints are barely visible in the light theme
this change applies the notification colors to inlay hints to change that

light: use notification colors for editor inlay hints

---

themes/Night Owl-color-theme-noitalic.json
themes/Night Owl-color-theme.json

Better colors for built-in editor inlay hints. They stand out waaaaay too much by default.
Original:
This PR:

feat: inlay hint colors for dark themes

---

README.md

[Ghostty](https://ghostty.org/) is a new terminal that had its public release a few days ago.
I've created the light and dark versions of the Night Owl theme for Ghostty and added them to [a single repository](https://https://github.com/m1yon/ghostty-night-owl).
Thank you for this fantastic theme 🙏

add Ghostty theme links to README
